BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Daily] (
    [id] INT NOT NULL IDENTITY(1,1),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Daily_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [date] DATETIME2 NOT NULL CONSTRAINT [Daily_date_df] DEFAULT CURRENT_TIMESTAMP,
    [content] VARCHAR(255) NOT NULL,
    CONSTRAINT [Daily_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
